In [2]:
from google.colab import files
uploaded = files.upload()

Saving cables_cost.xls to cables_cost.xls


In [4]:
# -*- coding: utf-8 -*-
"""
Exercicio 1: arvore geradora minima
Joao Victor de O. G Ribeiro - GES 106
"""

import numpy as np
from xlrd import open_workbook

m = 106

#Read input data from spreadsheet.
wb = open_workbook('cables_cost.xls')

for s in wb.sheets():
    number_of_nodes = 0
    for col in range(1,s.ncols):
        if (s.cell(0,col).value)!='':
            number_of_nodes = number_of_nodes + 1
            
#Create two dimensional matrix.
cables_cost_matrix = np.zeros((number_of_nodes,number_of_nodes), dtype=float)

for row in range(s.nrows):
    for col in range(s.ncols):
        if row > 0:
            value  = (s.cell(row,col).value)
            cables_cost_matrix[row-1,col-1] = value

print ('MATRIZ DE CUSTO DO EXERCICIO 1')
print (cables_cost_matrix, '\n')

#Multiplying the matrix by the enrollment number to get the actual cost
cost_matrix = cables_cost_matrix*m
print ('MATRIZ DE CUSTO COM OS VALORES REAIS DE ACORDO COM MINHA MATRICULA')
print (cost_matrix, '\n')

#Excluding 0 in cost matrix and convert it to list.
cost_matrix[cost_matrix == 0] = 10*cost_matrix.max()
cost = cost_matrix.tolist()
       
#Initialize lists for iteractions.     
not_connected = []
connected = []

#Start with all nodes not connected
for i in range(number_of_nodes):
    not_connected.append(i)

#First iteraction - start with first node
connected.append(min(not_connected)) #Include first not in connected.
not_connected.pop(not_connected.index(min(not_connected))) #Exclude first not
                                                           #from not_connected.

#Other iteractions
edge_from =[]
edge_to = []

total_cost = 0

while not_connected != []:

    temp_min = 10*cost_matrix.max() #Stablish a big value for starting.
    
    for i in connected:
        for j in not_connected:
            if cost[i][j] < temp_min:
                temp_min = cost[i][j]
                from_node = i
                to_node = j
    
    total_cost = total_cost + temp_min
    connected.append(to_node)
    not_connected.pop(not_connected.index(to_node))
    
    edge_from.append(from_node)
    edge_to.append(to_node)
    
#Print Arcs
print ('RESULTADO:', '\n')
print ('Custo total de implantação da rede: R$',total_cost, '\n')

print ('Arco/Cidade:')
for i in range(0,len(edge_from)):
    print ("Arco",i+1,":",'Cidade',edge_from[i]+1,"--->",'Cidade',edge_to[i]+1)


MATRIZ DE CUSTO DO EXERCICIO 1
[[0. 5. 3. 2. 0. 0.]
 [5. 0. 4. 0. 6. 0.]
 [3. 4. 0. 1. 3. 5.]
 [2. 0. 1. 0. 0. 2.]
 [0. 6. 3. 0. 0. 4.]
 [0. 0. 5. 2. 4. 0.]] 

MATRIZ DE CUSTO COM OS VALORES REAIS DE ACORDO COM MINHA MATRICULA
[[  0. 530. 318. 212.   0.   0.]
 [530.   0. 424.   0. 636.   0.]
 [318. 424.   0. 106. 318. 530.]
 [212.   0. 106.   0.   0. 212.]
 [  0. 636. 318.   0.   0. 424.]
 [  0.   0. 530. 212. 424.   0.]] 

RESULTADO: 

Custo total de implantação da rede: R$ 1272.0 

Arco/Cidade:
Arco 1 : Cidade 1 ---> Cidade 4
Arco 2 : Cidade 4 ---> Cidade 3
Arco 3 : Cidade 4 ---> Cidade 6
Arco 4 : Cidade 3 ---> Cidade 5
Arco 5 : Cidade 3 ---> Cidade 2
